# Generated by Django 5.0.3 on 2025-04-15 03:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="payment_status",
            new_name="status",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="amount_paid",
        ),
        migrations.AddField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
